### ISSUE TITLE
test reaper / socialreaper

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/smo-wiki#45]
https://github.com/ScriptSmith/socialreaper

https://reaper.social

**Comment by Khandoker09** [comment]
#  [Reaper](https://reaper.social/)

Reaper is an API based tool for social media analysis. It is useful for people with less programming knowledge. It has its own GUI and supports almost all common social media. Also, it's a multiplatform tool. To use this tool, first [download](https://github.com/ScriptSmith/reaper/releases) the software for the operating system. Additionally you will need the respective [api key](https://community.funnelback.com/knowledge-base/implementation/Gather-And-Index/custom-gatherer/social-media-api-keys) for the specific social media platform you need data from. Then input the API keys in the reaper software. Next, add a query and count. Then you can start querying and downloading the data into CSV forma.

## Features

- supports Facebook, Twitter, Reddit, Youtube, Tumblr, and Pinterest (however we have tested only Twitter so far)
- supports both in macOS and Windows
- uses .CSV type data format.
- user interface 

## Limitations

- to use this software, the user has to have a developer account for the social media platforms to get API keys
- Facebook has more scraping options than other social media
- since it is using the normal developer API, it has the common API rate limits

#### Last tested 

10/05/2021

**Comment by FlxVctr** [comment]
add to the tested platform sections as discussed (Twitter and misc)

**Comment by vomJupiter** [comment]
somehow reaper ended up on the tool list for instagram instead of twitter/facebook. was that on purpose or does this needs to be fixed, @FlxVctr ?

**Comment by FlxVctr** [comment]
Actually, I think this needs to be tested again anyway, the last commit seems to have been in 2019. Then it should be on all platform categories that apply or still work.

**Comment by vomJupiter** [comment]
removed Reaper from tool list. seems attractive just for FB data but is API based. therefore there is no usecase
